Repository ti-community-infra/test-dev, pull requests merged in 2021-09, with the labels that each got.

#424 feat: add config
  config/config.toml.example
  sessionctx/variable/tidb_vars.go
Labels: status/LGT1, status/can-merge, size/XXL

#428 [Fixed #426][docs] add commands to trigger ci doc (#428)
  ddddd
Labels: status/LGT1, size/XS, status/can-merge

#431 feat: tars test 3
  README.md
  ddddd
  dsada
Labels: status/LGT1, size/XS, status/can-merge, do-not-merge/hold

#432 test: Merge test
  README.md
  ddddd
Labels: status/LGT1, size/XS, status/can-merge

#434 feat: make a pr merge to master for tars triggered by push event
  README.md
Labels: status/LGT1, size/XS, status/can-merge

#435 feat: make commit for tars comment event test
  README.md
Labels: status/LGT1, size/XS, status/can-merge

#436 feat: make commit for tars cronjob test
  README.md
Labels: status/LGT1, size/XS, status/can-merge

#429 feat: tars-test-1
  ddddd
Labels: status/LGT1, size/XS, status/can-merge

#437 feat: Create pull_request_template.md
  .github/pull_request_template.md
Labels: status/LGT1, status/can-merge, size/M

#440 [Fixed #438] *: fix bug
  ddddd
Labels: status/LGT1, size/XS, status/can-merge

#441 [Fixed #438] *: fix bug
  dsada
Labels: status/LGT1, status/can-merge

#444 feat: create CODEOWNERS
  CODEOWNERS
Labels: status/LGT1, size/XS, status/can-merge

#443 feat: Update ddddd
  ddddd
  dsada
Labels: status/LGT1, size/XS, status/can-merge

#450 feat: add code owners
  CODEOWNERS
Labels: status/LGT1, size/XS, status/can-merge

#453 feat: modify codeowners
  CODEOWNERS
Labels: status/LGT1, size/XS, status/can-merge

#456 feat: update codeowners
  CODEOWNERS
Labels: status/LGT1, size/XS, status/can-merge

#458 test: add test 2
  dsada
Labels: status/LGT1, size/XS, status/can-merge

#459 feat: modify var both
  config/config.toml.example
  sessionctx/variable/tidb_vars.go
Labels: status/LGT1, size/XS, status/can-merge, contribution, needs-ok-to-test, first-time-contributor
