Repository ti-community-infra/test-dev, pull requests merged in 2021-07, with the labels that each got.

#403 test: delete c
  c
Labels: size/S, status/LGT1, status/can-merge

#402 test: delete a
  a
Labels: size/XS, status/LGT1, status/can-merge

#404 feat: Create cherry_picker_test.md
  cherry_picker_test.md
Labels: size/XS, status/LGT1, status/can-merge

#406 feat: update README
  README.md
Labels: cherrypick/config, size/XS, status/LGT1, status/can-merge

#408 test: test cherry-pick
  ddddd
Labels: cherrypick/config, cherrypick/test39, cherrypick/test43, cherrypick/testc, size/XS, status/LGT1, status/can-merge
